name: integration_tests

on:
  push:
    # branches:
    #   - main
  pull_request:

# concurrency:
#   group: integration_tests-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

env:
  PYTHON_VERSION: 3.8.5
  PIP_VERSION: 20.2.4
  REQUIREMENTS_PATH: "internal/buildscripts/packaging/tests/requirements.txt"
  RESULT_PATH: "~/testresults"
  GO_VERSION: 1.17.2

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      # - name: Pull in kong-plugin-signalfx
      #   run: git submodule update --init --recursive --remote

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -yq python3-pip
          sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

          git clone https://github.com/pyenv/pyenv.git ~/.pyenv

          sudo echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          sudo echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          sudo echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc

          sudo ls -la
          sudo cat ~/.bashrc
          
          source ~/.bashrc

          pyenv install 3.5.2
          pyenv local 3.5.2
          pip3 install tox
      
      - name: Run integration tests
        run: tox -e integration
