name: integration_tests

on:
  push:
    # branches:
    #   - main
  pull_request:

# concurrency:
#   group: integration_tests-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

env:
  PYTHON_VERSION: 3.8.5
  PIP_VERSION: 21.3.1
  REQUIREMENTS_PATH: "internal/buildscripts/packaging/tests/requirements.txt"
  RESULT_PATH: "~/testresults"
  GO_VERSION: 1.17.2

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull in kong-plugin-signalfx
        run: |
          git config --list
          git submodule update --init --recursive --remote
          git config --list
          ls -la test/integration/sfx/

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -yq python3-pip
          sudo apt-get install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

          curl https://pyenv.run | bash
          echo 'export PATH="~/.pyenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

          sudo cat ~/.bashrc

          . ~/.bashrc

          pyenv install 3.8.10
          pyenv global 3.8.10
          pip3 install tox

      # - name: setup pyenv
      #   id: pyenv_installation
      #   uses: "gabrielfalcao/pyenv-action@v5"
      #   with:
      #     default: 3.7.5
      #     command: |
      #       pip install -U pip setuptools

      # - name: Create virtualenv for python 3.7.5
      #   run: pyenv local 3.7.5 && python3 -mvenv .venv375

      # - name: Install dependencies
      #   run: pip install tox

      - name: List files
        run: sudo ls -la ~/
      
      - name: Run integration tests
        run: tox -e integration
