name: integration_tests

on:
  push:
    # branches:
    #   - main
  pull_request:

# concurrency:
#   group: integration_tests-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

env:
  PYTHON_VERSION: 3.8.5
  REQUIREMENTS_PATH: "internal/buildscripts/packaging/tests/requirements.txt"
  RESULT_PATH: "~/testresults"
  GO_VERSION: 1.17.2

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull in kong-plugin-signalfx
        run: |
          git submodule update --init --recursive --remote

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -yq python3-pip
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

          curl https://pyenv.run | bash
          export PATH="~/.pyenv/bin:$PATH" >> ~/.bashrc
          eval "$(pyenv init -)" >> ~/.bashrc
          eval "$(pyenv virtualenv-init -)" >> ~/.bashrc

          source ~/.bashrc

          pyenv install 3.5.3
          pyenv global 3.5.3
          pyenv virtualenv 3.5.3 env
          pip --version
          pip3 -V
          python --version
          pip3 install tox
      
      # - name: Run integration tests
      #   run: tox -e integration
