name: integration_tests

on:
  push:
    # branches:
    #   - main
  pull_request:

# concurrency:
#   group: integration_tests-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

env:
  PYTHON_VERSION: 3.8.5
  PIP_VERSION: 21.3.1
  REQUIREMENTS_PATH: "internal/buildscripts/packaging/tests/requirements.txt"
  RESULT_PATH: "~/testresults"
  GO_VERSION: 1.17.2

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull in kong-plugin-signalfx
        run: |
          git submodule update --init --recursive --remote
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install tox

      # - name: setup pyenv
      #   id: pyenv_installation
      #   uses: "gabrielfalcao/pyenv-action@v5"
      #   with:
      #     default: 3.7.5
      #     command: |
      #       pip install -U pip setuptools

      # - name: Create virtualenv for python 3.7.5
      #   run: pyenv local 3.7.5 && python3 -mvenv .venv375

      # - name: Install dependencies
      #   run: pip install tox

      # - name: List files
      #   run: | 
      #     sudo ls -la /usr/bin/
      #     which python
      #     python --version
      
      - name: Run integration tests
        run: tox -e integration
